### ISSUE TITLE
Getting Deserialise error after autherising the app

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-getting-started-dotnet#18]
Getting Deserialise error after autherising the app

![screenshot_2019-01-07-10-06-14-770_net maidsafe safetodoexample](https://user-images.githubusercontent.com/27578024/50894245-bf2aa080-1428-11e9-86c8-d83b33c7fc4b.png)

**Comment by ravinderjangra** [comment]
@safesurfer It's occurring because now we are encrypting all the data so when it is trying to fetch and decrypt we are getting this error.

**Comment by S-Coyle** [comment]
At standup on 09/01 discussed with @safesurfer and @ravinderjangra alternative ways to test this without hitting the issue seen which was due to bad (incompatible) data - e.g. different user account.
Should be verified as not an issue
